#!/usr/bin/env bash
# supervise.sh — Background supervisor daemon for agent lifecycle monitoring
# Usage: supervise.sh <run-dir> [interval-seconds]
#
# Runs as a background process, continuously monitoring all registered agents.
# State files: <run-dir>/supervisor/agents/<agent>.state
# Event log:   <run-dir>/supervisor/events.log
# PID file:    <run-dir>/supervisor/pid
#
# Start: supervise.sh ".Agent_ChatRoom/.../RUN-xxx" 15 &
# Stop:  sup-stop.sh ".Agent_ChatRoom/.../RUN-xxx"
#
# Agent state machine:
#   spawned → booting → ready → active → working → done
#                                        ↘ stalled (recoverable)
#                    ↘ timeout           ↘ timeout
#                                        ↘ crashed (pane gone)

set -euo pipefail

RUN_DIR="${1:?Usage: supervise.sh <run-dir> [interval]}"
INTERVAL="${2:-10}"
SUP_DIR="${RUN_DIR}/supervisor"
AGENTS_DIR="${SUP_DIR}/agents"
EVENTS_LOG="${SUP_DIR}/events.log"
PID_FILE="${SUP_DIR}/pid"

mkdir -p "$AGENTS_DIR"

# ─── Singleton guard ────────────────────────────────────────────────
if [ -f "$PID_FILE" ]; then
  OLD_PID=$(cat "$PID_FILE")
  if kill -0 "$OLD_PID" 2>/dev/null; then
    echo "Supervisor already running (PID $OLD_PID)" >&2
    exit 0
  fi
  rm -f "$PID_FILE"
fi
echo $$ > "$PID_FILE"

# ─── Graceful shutdown ──────────────────────────────────────────────
cleanup() {
  log_event "supervisor" "running→stopped" "shutdown signal received"
  rm -f "$PID_FILE"
  exit 0
}
trap cleanup SIGTERM SIGINT SIGPIPE

# ─── Helpers ────────────────────────────────────────────────────────
log_event() {
  local agent="$1" transition="$2" detail="${3:-}"
  printf '%s [%s] %s — %s\n' "$(date -Iseconds)" "$agent" "$transition" "$detail" \
    >> "$EVENTS_LOG"
}

# Read state file into shell variables (safe: all values written by our code)
# After calling this: STATUS, TMUX_TARGET, DISPATCH_FILE, DONE_FILE,
# STARTED_AT, LAST_SEEN_AT, LAST_CHANGE_AT, PANE_HASH, IDLE_CHECKS are set.
STATE_FILE=""
read_state() {
  local agent="$1"
  STATE_FILE="${AGENTS_DIR}/${agent}.state"
  if [ ! -f "$STATE_FILE" ]; then return 1; fi
  STATUS="" TMUX_TARGET="" DISPATCH_FILE="" DONE_FILE=""
  STARTED_AT=0 LAST_SEEN_AT=0 LAST_CHANGE_AT=0 PANE_HASH="" IDLE_CHECKS=0
  # Safe source: all values are generated by sup-reg.sh and this script
  # shellcheck disable=SC1090
  source "$STATE_FILE"
}

write_state() {
  local tmp="${STATE_FILE}.tmp"
  cat > "$tmp" << EOF
STATUS=${STATUS}
TMUX_TARGET=${TMUX_TARGET}
DISPATCH_FILE=${DISPATCH_FILE}
DONE_FILE=${DONE_FILE}
STARTED_AT=${STARTED_AT}
LAST_SEEN_AT=${LAST_SEEN_AT}
LAST_CHANGE_AT=${LAST_CHANGE_AT}
PANE_HASH=${PANE_HASH}
IDLE_CHECKS=${IDLE_CHECKS}
EOF
  mv "$tmp" "$STATE_FILE"
}

transition() {
  local agent="$1" new="$2" detail="${3:-}"
  local old="$STATUS"
  [ "$old" = "$new" ] && return
  STATUS="$new"
  LAST_CHANGE_AT=$(date +%s)
  log_event "$agent" "${old}→${new}" "$detail"
  write_state
}

# ─── Per-agent check cycle ──────────────────────────────────────────
check_agent() {
  local agent="$1"
  read_state "$agent" || return

  local now
  now=$(date +%s)
  LAST_SEEN_AT=$now

  # Terminal states: skip
  case "$STATUS" in done|failed|crashed|timeout) return ;; esac

  # ── Priority 1: DONE file ──
  if [ -f "$DONE_FILE" ]; then
    local done_status
    done_status=$(grep -oP '(?<=^status:\s).*' "$DONE_FILE" 2>/dev/null | head -1 || echo "done")
    case "$done_status" in
      failed|blocked) transition "$agent" "failed" "DONE reports ${done_status}" ;;
      *)              transition "$agent" "done"   "DONE file found" ;;
    esac
    return
  fi

  # ── Priority 2: Pane alive? ──
  local pane_output=""
  pane_output=$(tmux capture-pane -t "$TMUX_TARGET" -p -S -30 2>/dev/null || true)

  if [ -z "$pane_output" ]; then
    if ! tmux display-message -t "$TMUX_TARGET" -p '' &>/dev/null; then
      transition "$agent" "crashed" "tmux target unreachable"
      return
    fi
    # Pane exists but empty (fresh shell) — fall through
  fi

  # ── Priority 3: Output change detection ──
  local new_hash
  new_hash=$(printf '%s' "$pane_output" | md5sum | cut -d' ' -f1)

  local output_changed=false
  if [ -n "$PANE_HASH" ] && [ "$new_hash" != "$PANE_HASH" ]; then
    output_changed=true
  fi
  PANE_HASH="$new_hash"

  if $output_changed; then
    IDLE_CHECKS=0
  else
    IDLE_CHECKS=$((IDLE_CHECKS + 1))
  fi

  # ── State machine ──
  local elapsed=$(( now - STARTED_AT ))
  local since_change=$(( now - LAST_CHANGE_AT ))

  case "$STATUS" in
    spawned)
      # mpi should have been sent; give it a moment then move to booting
      if [ "$elapsed" -gt 5 ]; then
        transition "$agent" "booting" "waiting for Pi CLI"
      fi
      ;;

    booting)
      # Detect Pi CLI readiness indicators
      if printf '%s' "$pane_output" | grep -qE '(0\.0%/|Cursor|Update Available|^\S+.*\(.*\)\s*$)' 2>/dev/null; then
        transition "$agent" "ready" "Pi CLI detected in pane"
      elif [ "$since_change" -gt 60 ]; then
        transition "$agent" "timeout" "Pi CLI not detected after ${since_change}s"
      fi
      ;;

    ready)
      # Agent switch + task dispatch should produce output
      if $output_changed; then
        transition "$agent" "active" "agent responding to task"
      elif [ "$since_change" -gt 120 ]; then
        transition "$agent" "timeout" "agent never became active after ${since_change}s"
      fi
      ;;

    active)
      if $output_changed; then
        transition "$agent" "working" "output detected"
      elif [ "$IDLE_CHECKS" -gt 12 ]; then
        # ~12 * INTERVAL seconds with no output change
        transition "$agent" "stalled" "no output change for $((IDLE_CHECKS * INTERVAL))s"
      fi
      ;;

    working)
      if [ "$IDLE_CHECKS" -gt 30 ]; then
        transition "$agent" "stalled" "no output change for $((IDLE_CHECKS * INTERVAL))s"
      fi
      ;;

    stalled)
      # Recoverable: if output resumes, go back to working
      if $output_changed; then
        transition "$agent" "working" "output resumed after stall"
      fi
      ;;
  esac

  write_state
}

# ─── Main loop ──────────────────────────────────────────────────────
log_event "supervisor" "stopped→running" "interval=${INTERVAL}s pid=$$"

while true; do
  for state_file in "$AGENTS_DIR"/*.state; do
    [ -f "$state_file" ] || continue
    local_agent=$(basename "$state_file" .state)
    check_agent "$local_agent"
  done
  sleep "$INTERVAL"
done
